// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blogs: dynamic(() => import("./Blogs")),
  companies: dynamic(() => import("./Companies")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  pricing: dynamic(() => import("./Pricing")),
  testimonials: dynamic(() => import("./Testimonials")),
};
